import "./global.scss";
import Header from "@/components/frame/header";
import Footer from "@/components/frame/footer";
import { MSGraphClient } from "@/lib/ms-graph/client";
import { HFApp } from "@/lib/app";
import { protectRoutes } from "@/lib/protectRoutes";

export const metadata = {
  title: "HF's Recipes",
  description: "Generated by Next.js",
};

HFApp.ensureInitialized();

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className="dark:bg-slate-800 text-gray-800 dark:text-gray-200">
        {children}
      </body>
    </html>
  );
}
