import Loading, { LoadingSkeletonType } from "@/components/loading";
import { HFApp } from "@/lib/app";
import { Analytics } from "@vercel/analytics/react";
import { Suspense } from "react";
import "./global.scss";

export const metadata = {
    title: "HF's Recipes",
    description: "Generated by Next.js"
};

HFApp.ensureInitialized();

export default function Layout({ children }) {
    return (
        <html lang="en">
            <head>
                <meta
                    name="google-adsense-account"
                    content="ca-pub-2275811890061218"
                />
            </head>
            <body className="text-gray-800 dark:bg-slate-800 dark:text-gray-200">
                <Suspense
                    fallback={<Loading type={LoadingSkeletonType.text} />}
                >
                    {children}
                </Suspense>
                <Analytics />
            </body>
        </html>
    );
}
